name: net CI
on:
  push:
    paths:
      - "**ci.yml"
      - "**.hpp"
      - "**.cpp"
      - "**CMakeLists.txt"
  pull_request:
    paths:
      - "**ci.yml"
      - "**.hpp"
      - "**.cpp"
      - "**CMakeLists.txt"

jobs:
  linux:
    name: Linux ${{matrix.arch}} (${{matrix.gcc-version}})
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64]
        gcc-version: ["g++-9", "g++10", "g++-11", "g++-12"]
        os: ["ubuntu-22.04"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y cmake ${{ matrix.gcc-version }} libssl-dev ninja-build rpm

      - name: Configure CMake
        run: cmake -S . -B build -G Ninja
        env:
          CXX: ${{matrix.gcc-version}}

      - name: Build
        run: cmake --build build --config Release

      - name: Package
        run: cd build && cpack --verbose

      - name: Upload Binary (DEB)
        uses: actions/upload-artifact@v3
        with:
          name: "libnet - Debian Package ${{matrix.arch}}"
          path: "${{github.workspace}}/build/*.deb"

      - name: Upload Binary (RPM)
        uses: actions/upload-artifact@v3
        with:
          name: "libnet - RPM Package ${{matrix.arch}}"
          path: "${{github.workspace}}/build/*.rpm"
  windows:
    strategy:
      fail-fast: false
      matrix:
        arch: [x64, x86]
        config: [Release, Debug]

    name: "Windows ${{matrix.arch}}-${{matrix.config}}-vs2022"
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Configure CMake (x64)
        if: ${{ matrix.arch == 'x64' }}
        run: cmake -S . -B build -G "Visual Studio 17 2022"

      - name: Configure CMake (x86)
        if: ${{ matrix.arch == 'x86' }}
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A Win32 -T host=x86

      - name: Build
        run: cmake --build build --config ${{matrix.config}}

      - name: Package
        run: cd build && cpack -C ${{matrix.config}} --verbose

      - name: Upload Binary
        uses: actions/upload-artifact@v3
        with:
          name: "libnet - Windows ${{matrix.arch}}-${{matrix.config}}-vs2022"
          path: "${{github.workspace}}/build/*.zip"
